### ISSUE TITLE
How to individually access stat scores in template.

### ISSUE THREAD

**Issue by Bugmaniac71** [ebullient/json5e-convert-cli#34]
How to individually access stat scores in template (including the bonus's).

So for example:
 If I want to use an info box to reformat and add in Dice Roller functionality:
> [!infobox]
> ###### Stats
> | Type |  Stat |
> | ---- | ---- |
> |**STR**|19 (+3) `dice: 1d20 +3`|

Ideally I could access this with 
>|**STR**|{resource.str} ({resource.strbonus}) `dice: 1d20 {resource.strbonus}`|

Thoughts?
C

**Comment by ebullient** [comment]
yes. I think I would probably wrap it in stats instead of scores (scores would keep giving you the current string... stats would give you the parts.

Would be wrapping exposing this: https://github.com/ebullient/json5e-convert-cli/blob/main/src/main/java/dev/ebullient/json5e/qute/AbilityScores.java ...

**Comment by ebullient** [comment]
Fixed by 5e798498f9c24d59d364a50b796b018795492e60

**Comment by Bugmaniac71** [comment]
Almost works perfectly, very close ;->

Tried testing with Goblin. Negative value in the modifier works but Zero or Positive mod doesnt get added to the dice roll:

- STR:  8 (-1) `dice: 1d20 -1`
- DEX: 14 (+2) `dice: 1d20 2` 
- CON: 10 (+0) `dice: 1d20 0` 

C

**Comment by ebullient** [comment]
oh. because I didn't decorate the value anymore (not a string). Woops.

**Comment by Bugmaniac71** [comment]
Works perfectly now thanks!
