### ISSUE TITLE
Monster names as links for 5e Statblocks?

### ISSUE THREAD

**Issue by cjolson** [ebullient/json5e-convert-cli#76]
If the name of the monster in the YAML is a link to the monster note, then it would be helpful for accessing the relevant monster file quickly from the initiative tracker Combatant window or from the Statblocks itself. Currently it is not a link and I don't think I can easily make that change in the template for my monsters.

**Comment by ebullient** [comment]
@valentine195 .. what do you think we can do with this?

**Comment by valentine195** [comment]
Could `statblock-link` work for this?

**Comment by ebullient** [comment]
Resolved by https://github.com/valentine195/obsidian-5e-statblocks/pull/126 and https://github.com/valentine195/obsidian-5e-statblocks/pull/127

**Comment by ebullient** [comment]
`statblock-link` now works for links that are just anchors: `statblock-link: "#^statblock"`

There is an option to embed the block target into the creature view of Initiative tracker (instead of the rendered statblock). It is no longer necessary to have blocks in both the header and the body.. the minimal initiative tracker block works.
